"""initial

Revision ID: 782c45ca4764
Revises: 
Create Date: 2021-04-26 19:36:42.458352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782c45ca4764'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example_user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('example_meta_table',
    sa.Column('meta_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('contact', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['meta_id'], ['example_user_table.id'], ),
    sa.UniqueConstraint('contact')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('example_meta_table')
    op.drop_table('example_user_table')
    # ### end Alembic commands ###
